version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # For debugging purposes
      - ls -al
      - npm --version
      - node --version

  pre_build:
    commands:
      - ./install.sh

  build:
    commands:
      # Deploy
      ./deploy.sh $ENVIRONMENT $LANGUAGE $AUTH

artifacts:
  base-directory: cdk/cdk.out
  files:
    - "**/*"
