version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # For debugging purposes
      - ls -al
      - npm --version
      - node --version
      # Install dependencies
      - npm install -g aws-cdk
      - ./install.sh

  pre_build:
    commands:
      - ./test.sh

  post_build:
    commands:
      - ./install.sh --production

  build:
    commands:
      # Deploy
      ./deploy.sh $ENVIRONMENT $LANGUAGE $AUTH

artifacts:
  base-directory: cdk/cdk.out
  files:
    - "**/*"
