version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # For debugging purposes
      - ls -al
      - npm --version
      - node --version

  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - echo "node use 18"
      - n 18
      - ./install.sh
      - ./check-license.sh
      - ./test.sh

  build:
    commands:
      # Deploy
      ./deploy.sh $ENVIRONMENT $LANGUAGE $AUTH $CNAME

artifacts:
  base-directory: cdk/cdk.out
  files:
    - "**/*"
