/*
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  SPDX-License-Identifier: Apache-2.0
 */

import {
    IBucket,
    Bucket,
    BucketEncryption,
    HttpMethods,
    ObjectOwnership,
} from "aws-cdk-lib/aws-s3";
import { Effect, PolicyStatement, AnyPrincipal } from "aws-cdk-lib/aws-iam";
import { Construct } from "constructs";

interface Props {
    contentBucketName: string;
    serverAccessLogsBucket: IBucket;
}

export class ContentStorage extends Construct {
    public readonly contentBucket: Bucket;

    constructor(scope: Construct, id: string, props: Props) {
        super(scope, id);

        this.contentBucket = new Bucket(scope, "ContentBucket", {
            encryption: BucketEncryption.S3_MANAGED,
            versioned: true,
            serverAccessLogsBucket: props.serverAccessLogsBucket,
            serverAccessLogsPrefix: "content_bucket/",
            objectOwnership: ObjectOwnership.OBJECT_WRITER,

            /**
             * Ideally, one would leave the bucket name to be autogenerated by CF. But
             * sometimes that creates circular dependencies and the only way to handle
             * them is to have a predictable resource name.
             *
             * Source:
             * https://aws.amazon.com/blogs/infrastructure-and-automation/handling-circular-dependency-errors-in-aws-cloudformation
             *
             * In this case, this bucket is being referenced in the Auth stack to give
             * Cognito Auth Role permissions to read/write to it, but the Backend stack
             * already has a dependency on the Auth stack due to the Cognito User Pool,
             * hence we cannot make the Auth stack depend on the Backend stack or a
             * circular dependency is created.
             */
            bucketName: props.contentBucketName,
            /**
             * CORS policy taken from Amplify Docs.
             * This bucket policy allows file uploads from the web browser.
             * https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-CorsRule.html
             */
            cors: [
                {
                    maxAge: 3000,
                    allowedOrigins: ["*"],
                    allowedHeaders: ["*"],
                    allowedMethods: [
                        HttpMethods.GET,
                        HttpMethods.HEAD,
                        HttpMethods.PUT,
                        HttpMethods.POST,
                        HttpMethods.DELETE,
                    ],
                    exposedHeaders: [
                        "x-amz-server-side-encryption",
                        "x-amz-request-id",
                        "x-amz-id-2",
                        "x-amz-meta-filename",
                        "ETag",
                    ],
                },
            ],
        });

        this.contentBucket.addToResourcePolicy(
            new PolicyStatement({
                effect: Effect.DENY,
                actions: ["s3:*"],
                principals: [new AnyPrincipal()],
                resources: [this.contentBucket.arnForObjects("*")],
                conditions: {
                    Bool: {
                        "aws:SecureTransport": false,
                    },
                },
            }),
        );
    }
}
