#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./add-license.sh
./generate-attributions.sh
./check-license.sh

bash -c "pushd backend && npm run lint-src && popd"
bash -c "pushd frontend && npm run lint-src && popd"
bash -c "pushd cdk && npm run lint-src && popd"
