# Workflow that runs end-to-end (E2E) tests every day against Gamma

name: E2E Tests

on:
  push:
    branches:
      - mainline-dev

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: mainline-dev

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Enter e2e-tests directory
      - run: cd e2e-tests

      # Run tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          config: baseUrl=https://gamma.badger.wwps.aws.dev/,defaultCommandTimeout=20000,pageLoadTimeout=100000,
          env: username=${{secrets.E2E_TEST_USERNAME}},password=${{secrets.E2E_TEST_PASSWORD}}
