# Workflow that runs prettier code style check.

name: Code Style Check

on:
  pull_request:
    branches:
      - mainline
      - mainline-dev

jobs:
  prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install prettier
      - run: npm install -g prettier

      # Check for frontend code style
      - run: prettier --check "frontend/src/**/*.tsx" "frontend/src/**/*.ts"

      # Check for backend code style
      - run: prettier --check "backend/src/**/*.ts"

      # Check for cdk code style
      - run: prettier --check "cdk/lib/**/*.ts" "cdk/bin/**/*.ts"
