# Workflow that runs unit tests on a new pull request to mainline.

name: Unit Tests

on:
  pull_request:
    branches:
      - mainline
      - mainline-dev

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install npm dependencies
      - run: ./install.sh

      # Run unit tests
      - run: ./test.sh
